### ISSUE TITLE
Embedded WebVOWL not generating visualization

### ISSUE THREAD

**Issue by JohannesLipp** [dgarijo/Widoco#433]
**Describe the bug**
After running Widoco w/ `-webVOWL` in a GitLab pipeline, the embedded WebVOWL visualization does not visualize anything on the GitLab page.

**To Reproduce**
1. Have the [foaf ontology](http://xmlns.com/foaf/spec/20140114.rdf) in a GitLab repository
2. Have a file `Gemfile` in that repo w/ the content:
```
source "https://rubygems.org"
gem "jekyll"
```
3. Have this `.gitlab-ci.yml` in the repo: 
```
image: ruby:2.7


pages:
  script:
    - echo "Installing Java..."
    - apt-get update
    - apt-get -y install default-jdk

    - echo "Creating documentation..."
    - wget https://github.com/dgarijo/Widoco/releases/download/v1.4.14/widoco-1.4.14-jar-with-dependencies.jar -O widoco.jar
    - java -jar widoco.jar -ontFile 20140114.rdf -outFolder ./  -webVowl -oops -rewriteAll -htaccess

    - echo "Creating pages..."
    - gem install bundler
    - bundle install
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public
  only:
    - master
```
4. Commit to mater branch and wait for the pipeline to succeed.
5. Go to your GitLab page (e.g., from the settings/pages/ screen) and see the documentation website.
6. See the website as expected, but with the WebVOWL part at the end of section 2 not visualizing the ontology.

**Expected behavior**
The embedded WebVOWL should visualize the ontology, like it does when I upload it to the [public WebVOWL page](http://www.visualdataweb.de/webvowl/).

**Screenshots**
The documentation works as expected...
![image](https://user-images.githubusercontent.com/15930331/98093912-da319480-1e88-11eb-8372-187eb27b6dcb.png)

...but the WebVOWL part does not work as expected (removed parts to ease visibility on the screenshot):
![image](https://user-images.githubusercontent.com/15930331/98093961-ed446480-1e88-11eb-9e23-1280d1b00933.png)

**Desktop (please complete the following information):**
 - Live GitLab instance at gitlab.com
 - Latest Chrome + Latest Firefox

**Additional context**
Using Widoco 1.4.14
